import React, { useState ,setState} from 'react';
import Head from 'next/head'
import Script from 'next/script'

const Contact = () => {



    const [state, setState] = useState({
        name: "",
        email: "",
        phone: "",
        comment: "",
      })

    const handleChange = evt => {
        const name = evt.target.name;
        const value =
        evt.target.type === "checkbox" ? evt.target.checked : evt.target.value;
        setState({
          ...state,
          [name]: value
        })
      }


    const handleSubmit=(e)=>{
        e.preventDefault();
        console.log(state)

        fetch('https://react-my-burger-f2d46.firebaseio.com/test.json', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify(state),
          })

          setState({
            name: "",
            email: "",
            phone: "",
            comment: "",
          })
      
     
    
    }

    return (
        
        <div>

            contact us

            <>
    <Head>
        <title>Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"/>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></Script>
    </Head>
            <form method='post' onSubmit={handleSubmit}>

            <div className="mb-3">
    <label className="form-label">Name </label>
    <input onChange={handleChange} value={state.name} type="text" className="form-control" id="name" name="name" />
  </div>
  <div className="mb-3">
    <label  className="form-label">Email address</label>
    <input  onChange={handleChange} value={state.email} type="email" className="form-control" id="email" name="email"/>
  </div>
  <div className="mb-3">
    <label className="form-label">Phone</label>
    <input  onChange={handleChange} value={state.phone} type="text" className="form-control" id="phone" name="phone"/>
  </div>

  <div className="mb-3">
    <label className="form-label">comment</label>
    <input type="textarea"  onChange={handleChange} className="form-control" id="comment" name="comment" rows="3" value={state.comment}/>
  </div>
  
  <button type="submit" className="btn btn-primary">Submit</button>
</form>
            </>
        </div>
    );
}

export default Contact;
